### ISSUE TITLE
List of regex patterns possible? 

### ISSUE THREAD

**Issue by gullpavon** [mesejo/trex#8]
First, great package. Love using it! Makes my life much easier, and the speed is phenomenal! 

I find that it works with a list of words, such as ['Love', 'Hello', ' Book',...]

Does it work with a list of regex patterns?

For example

```
regex_patterns = [
    r'(?!^\d+)(?=.*)(\b\d+$\b)'               #Remove any numbers that end string i.e "SHELL 545436"
   ,r'^\bSQ\b'                                #Remove the "SQ" if it starts the string ie. "SQ NORDSTROM"
   ,r'(?!\b(ST|^\w{1,2})\b$)\b\w{1,2}\b$'     #Remove any words that are one or two chars at end of string i.e. "Burger King CA" -- except if they = "ST"

]

tx_maker = tx.make(entity_final_clean_regex_patterns,  prefix=r"", suffix=r"") 


#clean column
df['clean'] = df.STRING_COLUMN.str.replace(tx_maker, "", regex=True)
```

**Comment by mesejo** [comment]
Hi @gullpavon! Thanks for opening an issue. Apologies for the late reply, sadly it won't work with list of regex patterns. I suggest you try with [hyperscan](https://intel.github.io/hyperscan/dev-reference/intro.html). It has a Python bindings package (see [here](https://github.com/darvid/python-hyperscan)).
